DROP TABLE IF EXISTS USR CASCADE;
CREATE TABLE USR(
	USR_ID SERIAL PRIMARY KEY,
	USERNAME VARCHAR (50) NOT NULL,
	PW VARCHAR(50) NOT NULL,
	FIRSTNAME VARCHAR (50) NOT NULL,
	LASTNAME VARCHAR (50) NOT NULL
);

DROP TABLE IF EXISTS ACCOUNT CASCADE;
CREATE TABLE ACCOUNT(
	ACC_ID SERIAL PRIMARY KEY,
	USR_ID INTEGER,
	ACC_TYPE INTEGER NOT NULL,
	NICKNAME VARCHAR (50),
	BALANCE NUMERIC (50),
	INTEREST NUMERIC (50) NOT NULL,
	ACTIVE NUMERIC (50) NOT NULL,
	
	FOREIGN KEY (USR_ID) REFERENCES USR(USR_ID) ON DELETE CASCADE	
 );

DROP TABLE IF EXISTS TRANSACTION CASCADE;
CREATE TABLE TRANSACTION(
	USR_ID INTEGER,
	ACC_ID INTEGER,
	ACC_NICKNAME VARCHAR (50),
	TRANS_TYPE INTEGER,
	AMOUNT INTEGER,
	NEWBAL INTEGER,
	TRANSDATE VARCHAR (50),
	
	FOREIGN KEY (USR_ID) REFERENCES USR(USR_ID) ON DELETE CASCADE,
	FOREIGN KEY (ACC_ID) REFERENCES ACCOUNT(ACC_ID) ON DELETE CASCADE
);


--DROP TABLE IF EXISTS TRANS CASCADE
--create table transactions(
--	ID serial primary key,
--	UserID integer,
--	AccountID integer,
--	foreign key (UserID) references Users(ID) on delete cascade,
--	foreign key (AccountID) references Accounts(ID) on delete cascade
--	);
	